import Head from 'next/head'
import NavbarTypeA from '@/components/navbarComponents/NavbarTypeA'
import BannerSlide from '@/components/bannerComponents/BannerSlide'
import OurServiceSection from '@/components/serviceComponents/OurServiceSection'
import GreatWorkTab from '@/components/workComponents/GreatWorkTab';
import CounterSection from '@/components/CounterSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-developer.ico" />
      </Head>

      <main>
        <NavbarTypeA/> 
        <BannerSlide/>
        <OurServiceSection/>
        <CounterSection/>
        <GreatWorkTab/>
        <div><p className='footer'>{`© 2020 </> `}<span className='bold'>Developer.</span> All Rights Reserved</p></div>
      </main>
    </>
  )
}
